In [414]:
import numpy as np
import pandas as pd
import os

In [415]:
dir(pd) # to see all functions in pandas

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [416]:
files = os.listdir('hepsiemlak') # to list all files in the 'hepsiemlak' directory
df = pd.concat([pd.read_csv(f"hepsiemlak/{file}") for file in files], ignore_index=True) # to read each CSV file into a pandas DataFrame and concatenate them into a single DataFrame, using a list comprehension to iterate over the sorted list of files and an f-string to construct the file path

In [417]:
print(df.info()) # to get a concise summary of the DataFrame, including the number of non-null entries and data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   img-link href                        9925 non-null   object
 1   photo-count                          9902 non-null   float64
 2   list-view-price                      9925 non-null   object
 3   list-view-date                       9791 non-null   object
 4   list-view-title                      23 non-null     object
 5   left                                 9925 non-null   object
 6   celly                                9925 non-null   object
 7   celly 2                              9925 non-null   object
 8   celly 3                              9925 non-null   object
 9   celly 4                              9712 non-null   object
 10  list-view-location                   9925 non-null   object
 11  img-wrp href                         5278 non-null   object
 12  he-lazy-image src                    9320 non-null   object
 13  img-wrp href 2                       198 non-null    object
 14  he-lazy-image src 2                  4851 non-null   object
 15  listing-card--owner-info__firm-name  5278 non-null   object
 16  listing-card--owner-info__name       1522 non-null   object
 17  he-icon href                         1348 non-null   object
 18  text-ellipsis                        1348 non-null   object
 19  he-lazy-image src 3                  173 non-null    object
 20  list-view-header                     9902 non-null   object
 21  wp-btn                               1821 non-null   object
dtypes: float64(1), object(21)
memory usage: 1.7+ MB
None

In [418]:
df.shape

(9925, 22)

In [419]:
df.head()

,img-link href,photo-count,list-view-price,list-view-date,list-view-title,left,celly,celly 2,celly 3,celly 4,...,he-lazy-image src,img-wrp href 2,he-lazy-image src 2,listing-card--owner-info__firm-name,listing-card--owner-info__name,he-icon href,text-ellipsis,he-lazy-image src 3,list-view-header,wp-btn
0,https://www.hepsiemlak.com/istanbul-sisli-merk...,60.0,27.0,07-03-2026,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,Kiralık Daire,Stüdyo,39 m²,39\n Yaşında,Bahçe Katı,...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,https://www.hepsiemlak.com/emlak-ofisi/akyildi...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,Akyıldız Emlak,Özcan\n Ak,NaN,NaN,NaN,NaN,NaN
1,https://www.hepsiemlak.com/istanbul-kadikoy-ko...,17.0,85.0,07-03-2026,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,Kiralık Daire,3 +\n 1,110 m²,3\n Yaşında,1. Kat,...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,NaN,NaN,Emlak Park Real Estate,NaN,[object Object],Hepsiemlak’ta Yeni Üye,NaN,NaN,NaN
2,https://www.hepsiemlak.com/istanbul-kadikoy-ca...,47.0,590.0,05-03-2026,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,Kiralık Daire,5 +\n 1,300 m²,Sıfır Bina,1. Kat,...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,https://www.hepsiemlak.com/emlak-ofisi/coldwel...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,Coldwell Banker Trio,Ela Tomris\n İlkgelen,NaN,NaN,NaN,NaN,NaN
3,https://www.hepsiemlak.com/istanbul-pendik-yen...,37.0,42.5,06-03-2026,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,Kiralık Daire,2 +\n 1,90 m²,8\n Yaşında,1. Kat,...,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,NaN,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,Emlak Park Real Estate,NaN,[object Object],Hepsiemlak’ta Yeni Üye,NaN,NaN,NaN
4,https://www.hepsiemlak.com/istanbul-bahcelievl...,6.0,35.0,06-03-2026,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,Kiralık Residence,Stüdyo,74 m²,4\n Yaşında,8. Kat,...,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,https://www.hepsiemlak.com/emlak-ofisi/camur-g...,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,Çamur Gayrimenkul,Çamur\n Gayrimenkul,[object Object],Hepsiemlak’ta Yeni Üye,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,NaN,NaN

In [420]:
df = df.drop(columns=['img-link href','photo-count','list-view-date','left','he-lazy-image src','img-wrp href 2','he-lazy-image src 2','listing-card--owner-info__firm-name','listing-card--owner-info__name','listing-card--owner-info__name','he-icon href','text-ellipsis','he-lazy-image src 3','list-view-header','wp-btn'])

In [421]:
df.head()

,list-view-price,list-view-title,celly,celly 2,celly 3,celly 4,list-view-location,img-wrp href
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,Stüdyo,39 m²,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.,https://www.hepsiemlak.com/emlak-ofisi/akyildi...
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,3 +\n 1,110 m²,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,https://www.hepsiemlak.com/emlak-ofisi/emlak-p...
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,5 +\n 1,300 m²,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,https://www.hepsiemlak.com/emlak-ofisi/coldwel...
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,2 +\n 1,90 m²,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.,https://www.hepsiemlak.com/emlak-ofisi/emlak-p...
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,Stüdyo,74 m²,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,https://www.hepsiemlak.com/emlak-ofisi/camur-g...

In [422]:
df = df.drop(columns=['img-wrp href'])

In [423]:
df.head()

,list-view-price,list-view-title,celly,celly 2,celly 3,celly 4,list-view-location
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,Stüdyo,39 m²,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,3 +\n 1,110 m²,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,5 +\n 1,300 m²,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,2 +\n 1,90 m²,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,Stüdyo,74 m²,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.

In [424]:
df.shape

(9925, 7)

In [425]:
df['celly'] = df['celly'].apply(lambda x: x.replace('Stüdyo','1+0')) # to replace the string 'Stüdyo' with '1+0' in the 'celly' column of the DataFrame using the apply method and a lambda function
df['celly'] = df['celly'].apply(lambda x: x.replace('\n','')) # to remove newline characters from the 'celly' column of the DataFrame using the apply method and a lambda function that replaces '\n ' and '\n' with an empty string
df['room'] = df['celly'].apply(lambda x: x.split('+')[0]).astype(int) # preparing df['room'] column;split function is used to datas with character we've choosed (for example "+"),astype is used to determine the variable type
df['living_room'] = df['celly'].apply(lambda x: x.split('+')[1]).astype(int) # and [0] and [1] means the variable will read 0.character after "+",or 1.character,whatever we choose

In [426]:
df['room'].unique() # we will try to find outliders

array([ 1,  3,  5,  2,  4,  6,  7,  9,  8, 13, 10, 12, 30, 15, 50, 16])

In [427]:
df['living_room'].unique() # find the outliders

array([  0,   1,   2,   3,   4,  13,  10, 140,   5,   7])

In [428]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   celly               9925 non-null   object
 3   celly 2             9925 non-null   object
 4   celly 3             9925 non-null   object
 5   celly 4             9712 non-null   object
 6   list-view-location  9925 non-null   object
 7   room                9925 non-null   int32
 8   living_room         9925 non-null   int32
dtypes: int32(2), object(7)
memory usage: 620.4+ KB

In [429]:
df = df.drop(columns=['celly']) # we dont need celly column anymore
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   celly 2             9925 non-null   object
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32
 7   living_room         9925 non-null   int32
dtypes: int32(2), object(6)
memory usage: 542.9+ KB

In [430]:
df.head()

,list-view-price,list-view-title,celly 2,celly 3,celly 4,list-view-location,room,living_room
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,39 m²,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.,1,0
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,110 m²,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,3,1
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,300 m²,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,5,1
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,90 m²,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.,2,1
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,74 m²,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0

In [431]:
df['celly 2'].unique()

array(['39 m²', '110 m²', '300 m²', '90 m²', '74 m²', '85 m²', '240 m²',
       '112 m²', '87 m²', '70 m²', '120 m²', '75 m²', '170 m²', '80 m²',
       '55 m²', '160 m²', '60 m²', '178 m²', '105 m²', '45 m²', '100 m²',
       '150 m²', '95 m²', '197 m²', '520 m²', '210 m²', '65 m²', '130 m²',
       '320 m²', '550 m²', '225 m²', '145 m²', '25 m²', '78 m²', '162 m²',
       '1.100 m²', '140 m²', '115 m²', '135 m²', '165 m²', '180 m²',
       '125 m²', '109 m²', '155 m²', '47 m²', '500 m²', '50 m²', '220 m²',
       '146 m²', '169 m²', '107 m²', '280 m²', '138 m²', '700 m²',
       '40 m²', '175 m²', '76 m²', '600 m²', '96 m²', '79 m²', '250 m²',
       '101 m²', '67 m²', '77 m²', '106 m²', '230 m²', '73 m²', '35 m²',
       '134 m²', '400 m²', '650 m²', '68 m²', '98 m²', '200 m²', '82 m²',
       '270 m²', '124 m²', '126 m²', '61 m²', '37 m²', '185 m²', '186 m²',
       '189 m²', '116 m²', '206 m²', '117 m²', '149 m²', '92 m²',
       '350 m²', '215 m²', '190 m²', '141 m²', '153 m²', '113 m²',
       '182 m²', '450 m²', '1.580 m²', '136 m²', '72 m²', '123 m²',
       '103 m²', '176 m²', '108 m²', '208 m²', '212 m²', '127 m²',
       '122 m²', '196 m²', '69 m²', '159 m²', '91 m²', '118 m²', '470 m²',
       '18 m²', '275 m²', '23 m²', '310 m²', '330 m²', '81 m²', '385 m²',
       '53 m²', '147 m²', '183 m²', '48 m²', '540 m²', '30 m²', '66 m²',
       '455 m²', '304 m²', '195 m²', '139 m²', '148 m²', '52 m²',
       '381 m²', '380 m²', '205 m²', '84 m²', '42 m²', '121 m²', '263 m²',
       '333 m²', '102 m²', '290 m²', '15 m²', '43 m²', '8.599 m²',
       '951 m²', '223 m²', '192 m²', '41 m²', '365 m²', '360 m²', '33 m²',
       '181 m²', '58 m²', '17 m²', '133 m²', '485 m²', '235 m²', '22 m²',
       '405 m²', '38 m²', '194 m²', '63 m²', '20 m²', '86 m²', '337 m²',
       '340 m²', '142 m²', '151 m²', '204 m²', '1.010 m²', '104 m²',
       '132 m²', '800 m²', '168 m²', '580 m²', '720 m²', '156 m²',
       '242 m²', '24 m²', '163 m²', '260 m²', '88 m²', '179 m²', '99 m²',
       '1.000 m²', '191 m²', '89 m²', '213 m²', '97 m²', '54 m²', '59 m²',
       '161 m²', '143 m²', '245 m²', '349 m²', '177 m²', '152 m²',
       '368 m²', '71 m²', '94 m²', '64 m²', '62 m²', '615 m²', '198 m²',
       '137 m²', '232 m²', '353 m²', '530 m²', '36 m²', '202 m²',
       '144 m²', '352 m²', '689 m²', '188 m²', '128 m²', '114 m²',
       '199 m²', '335 m²', '222 m²', '327 m²', '325 m²', '501 m²',
       '57 m²', '34 m²', '187 m²', '359 m²', '355 m²', '167 m²', '28 m²',
       '331 m²', '129 m²', '83 m²', '224 m²', '51 m²', '26 m²', '171 m²',
       '218 m²', '46 m²', '56 m²', '292 m²', '228 m²', '164 m²', '305 m²',
       '44 m²', '282 m²', '172 m²', '285 m²', '239 m²', '1.250 m²',
       '193 m²', '157 m²', '255 m²', '517 m²', '119 m²', '214 m²',
       '289 m²', '850 m²', '166 m²', '480 m²', '216 m²', '49 m²',
       '266 m²', '158 m²', '370 m²', '154 m²', '93 m²', '174 m²',
       '184 m²', '440 m²', '257 m²', '131 m²', '273 m²', '475 m²',
       '750 m²', '880 m²', '2.500 m²', '396 m²', '279 m²', '238 m²',
       '111 m²', '420 m²', '265 m²', '288 m²', '246 m²', '27 m²',
       '1.800 m²', '690 m²', '433 m²', '256 m²', '498 m²', '277 m²',
       '100.000 m²', '298 m²', '406 m²', '271 m²', '346 m²', '1.200 m²',
       '207 m²', '484 m²', '490 m²', '90.000 m²', '314 m²', '221 m²',
       '32 m²', '248 m²', '388 m²', '211 m²', '243 m²', '11 m²', '295 m²',
       '236 m²', '508 m²', '226 m²', '460 m²', '435 m²', '1.400 m²',
       '21 m²', '680 m²', '369 m²', '269 m²', '620 m²'], dtype=object)

In [432]:
df['celly 2'] =  df['celly 2'].apply(lambda x: x.replace('.','')) # we will replace . with space
df['celly 2'] =  df['celly 2'].apply(lambda x: x.replace(' m²','')).astype(int) # we will delete m2 and we will convert strings to int

In [433]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   celly 2             9925 non-null   int32
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32
 7   living_room         9925 non-null   int32
dtypes: int32(3), object(5)
memory usage: 504.1+ KB

In [434]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [435]:
df.rename(columns={'celly 2': 'area'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   area                9925 non-null   int32
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32
 7   living_room         9925 non-null   int32
dtypes: int32(3), object(5)
memory usage: 504.1+ KB

In [436]:
df.head()

,list-view-price,list-view-title,area,celly 3,celly 4,list-view-location,room,living_room
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,39,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.,1,0
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,110,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,3,1
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,300,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,5,1
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,90,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.,2,1
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,74,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0

In [437]:
df['list-view-price'].unique()

array([27.0, 85.0, 590.0, 42.5, 35.0, 45.0, 125.0, 110.0, 250.0, 28.5,
       72.0, 80.0, 50.0, 95.0, 22.0, 23.0, 38.0, 55.0, 29.0, 17.5, 60.0,
       15.0, 18.0, 32.0, 160.0, 59.5, 52.0, 200.0, 51.0, 43.0, 120.0,
       31.0, 30.0, 21.5, '125.000', '39.500', '120.000', '129.000',
       '28.000', '435.000', '46.000', '22.000', '95.000', '32.500',
       '13.500', '55.000', '23.000', '18.000', '75.000', '82.000',
       '45.000', '260.000', '27.000', '35.000', '40.000', '25.000',
       '39.000', '20.000', '51.000', '32.000', '30.000', '13.000',
       '27.500', '68.000', '37.900', '15.000', '12.500', '19.000',
       '22.500', '9.500', '90.000', '85.000', '33.500', '36.000',
       '30.500', '33.000', '9.750.000', '65.000', '25.500', '12.000',
       '17.000', '80.000', '700.000', '34.500', '26.500', '24.000',
       '240.000', '50.000', '100.000', '70.000', '60.000', '36.250',
       '16.750', '20.500', '575.000', '150.000', '42.000', '26.000',
       '37.000', '81.000', '140.000', '25.020', '45.750', '42.500',
       '24.500', '38.000', '21.500', '17.500', '57.000', '34.000',
       '175.000', '28.250', '67.000', '290.000', '650.000', '52.000',
       '49.000', '11.000', '195.000', '40.250', '57.500', '37.500',
       '47.500', '69.000', '110.000', '375.000', '170.000', '164.000',
       '73.000', '160.000', '31.000', '59.000', '16.500', '47.000',
       '79.000', '270.000', '77.000', '250.000', '10.000', '145.000',
       '43.000', '67.500', '9.000', '165.000', '36.500', '350.000',
       '53.000', '31.500', '40.500', '62.500', '255.000', '16.000',
       '29.900', '560.000', '74.000', '135.000', '14.000', '15.500',
       '58.000', '105.000', '51.500', '330.000', '130.000', '61.000',
       '235.000', '112.000', '96.000', '62.000', '19.500', '18.100',
       '47.950', '41.000', '200.000', '48.000', '72.000', '124.000',
       '30.250', '115.000', '93.000', '245.000', '83.000', '87.500',
       '21.000', '155.000', '18.500', '54.000', '98.000', '28.500',
       '52.500', '66.000', '210.000', '44.000', '99.000', '230.000',
       '239.000', '8.500', '32.100', '30.750', '63.000', '325.000',
       '400.000', '56.000', '56.500', '46.500', '500.000', '38.500',
       '65.500', '119.000', '35.750', '180.000', '190.000', '78.000',
       '29.000', '36.750', '29.500', '93.500', '23.500', '39.999',
       '84.000', '80.500', '15.999', '64.900', '300.000', '48.750',
       '87.000', '41.500', '64.500', '14.500', '132.900', '50.200',
       '16.000.000', '950.000', '48.500', '14.999', '11.750', '77.950',
       '44.250', '280.000', '28.750', '24.750', '157.500', '35.950',
       '44.500', '66.500', '755.000', '33.750', '97.900', '600.000',
       '18.900', '49.500', '23.950', '26.750', '97.500', '220.000',
       '40.750', '30.749', '15.001', '1.250.000', '43.500', '18.999',
       '84.950', '8.000', '37.300', '31.700', '37.250', '45.950',
       '450.000', '89.000', '34.700', '31.250', '11.500', '4.100.000',
       '45.500', '423.000', '320.000', '82.500', '125.500', '70.500',
       '69.500', '38.499', '275.000', '59.750', '99.500', '295.000',
       '127.000', '620.000', '64.000', '35.500', '204.000', '92.500',
       '520.000', '7.500', '1.000.000', '39.750', '425.000', '54.500',
       '480.000', '39.950', '92.000', '25.700', '252.000', '26.250',
       '1.500', '7.000', '6.000', '7.100', '2.500', '5.500', '900.000',
       '360.000', '17.350.000', '1.000', '5.000', '32.750', '29.250',
       '28.900', '133.000', '55.700', '71.000', '490.000', '102.000',
       '94.000', '84.999', 33.0, 100.0, 190.0, 20.0, 65.0, 56.5, 21.0,
       40.0, 70.0, 104.0, 26.5, 49.0, 25.5, 130.0, 105.0, 75.0, 84.999,
       48.0, 42.0, 47.0, 90.0, 230.0, 380.0, 66.0, 24.5, 94.0, 36.0, 41.5,
       26.0, 24.0, 22.5, 58.0, 13.5, 57.0, 25.0, 17.0, 46.0, 32.5,
       '104.000', '380.000', '76.500', '118.000', '88.000', '215.000',
       '335.000', '42.750', '310.000', '46.750', '47.750', '147.500',
       '179.000', '72.500', '185.000', '152.500', '550.000', '1.200.000',
       '77.500', '365.000', '21.250', '139.500', '225.000', '61.500',
       '26.001', '25.750', '76.000', '132.000', 41.0, 143.0, 71.0, 63.0,
       225.0, 77.0, 74.0, 550.0, 140.0, 99.0, 81.0, 165.0, 36.5, 34.0,
       19.0, 175.0, 49.5, 180.0, 1.0, 51.5, 155.0, 16.0, 350.0, 34.5,
       91.0, 72.5, 39.8, 540.0, 44.0, 67.0, 310.0, 760.0, 37.25, 20.5,
       76.0, 150.0, 35.001, 28.0, 650.0, 18.5, 57.5, 48.25, 115.0, 27.5,
       53.0, 83.0, 10.0, 37.0, 13.0, 185.0, 43.5, 69.0, 145.0, 54.0, 16.5,
       61.0, 14.0, 46.5, 82.0, 68.5, 62.5, 220.0, 37.5, 23.5, 137.5, 44.9,
       78.0, 59.0, 47.5, 64.5, 27.999, 56.0, 40.5, 39.0, 195.0, 62.0,
       68.0, 18.1, 67.5, 630.0, 88.0, 210.0, 117.5, 18.75, 260.0, 74.999,
       19.65, 35.5, 98.0, '129.500', '29.998', '35.300', '109.000',
       '239.500', '86.000', '138.000', '38.250', '86.900', '1.700.000',
       '98.500', '55.500', '79.500', '189.000', '134.000', '137.500',
       '3.850.000', '74.990', '97.000', '20.600', '2.350.000', '23.750',
       '1.375.000', '29.999', '590.000', '34.250', '39.900', '49.900',
       '370.000', '29.350', '156.000', '78.500', '59.500', '285.000',
       '19.900', '58.500', '19.750', 400.0, 29.5, 12.0, 58.5, 270.0,
       135.0, 32.1, 19.75, 300.0, 92.5, 7.5, 8.0, 450.0, 83.5, 535.0,
       245.0, 73.0, 93.0, 30.5, 39.5, 620.0, 410.0, 6.0, 320.0, 240.0,
       77.777, 87.0, 365.0, 79.0, 7.0, 86.0, 19.5, 52.5, 215.0, 38.5,
       31.5, 139.5, 170.0, 25.75, 119.0, 89.0, 178.5, 11.5, 45.5, 360.0,
       25.02, 290.0, 325.0, 79.5, 275.0, 850.0, 44.5, 38.75, 33.5, 735.0,
       11.0, 440.0, 9.0, '23.250', '26.850', '53.500', '485.000',
       '24.800', '2.850.000', '96.500', '149.999', '340.000', '49.999',
       '585.000', '24.250', '38.750', '20.750', '117.000', '6.500',
       '445.000', '69.900', '139.700', '205.000', '102.500', '50.500',
       '1.800.000', '33.200', '91.000', '680.000', '850.000', '18.200',
       '23.999', '3.800', '68.750', '17.999', '137.000', '390.000',
       '470.000', '249.000'], dtype=object)

In [438]:
df['celly 3'].unique()

array(['39\n                        Yaşında',
       '3\n                        Yaşında', 'Sıfır Bina',
       '8\n                        Yaşında',
       '4\n                        Yaşında',
       '50\n                        Yaşında',
       '30\n                        Yaşında',
       '11\n                        Yaşında',
       '32\n                        Yaşında',
       '40\n                        Yaşında',
       '17\n                        Yaşında',
       '6\n                        Yaşında',
       '16\n                        Yaşında',
       '12\n                        Yaşında',
       '35\n                        Yaşında',
       '28\n                        Yaşında',
       '20\n                        Yaşında',
       '10\n                        Yaşında',
       '31\n                        Yaşında',
       '5\n                        Yaşında',
       '21\n                        Yaşında',
       '33\n                        Yaşında',
       '29\n                        Yaşında',
       '15\n                        Yaşında',
       '7\n                        Yaşında',
       '1\n                        Yaşında',
       '25\n                        Yaşında',
       '22\n                        Yaşında',
       '18\n                        Yaşında',
       '9\n                        Yaşında',
       '45\n                        Yaşında',
       '55\n                        Yaşında',
       '13\n                        Yaşında',
       '110\n                        Yaşında',
       '41\n                        Yaşında',
       '19\n                        Yaşında',
       '49\n                        Yaşında',
       '26\n                        Yaşında',
       '42\n                        Yaşında',
       '60\n                        Yaşında',
       '2\n                        Yaşında',
       '14\n                        Yaşında',
       '24\n                        Yaşında',
       '27\n                        Yaşında',
       '23\n                        Yaşında',
       '34\n                        Yaşında',
       '38\n                        Yaşında',
       '65\n                        Yaşında',
       '43\n                        Yaşında',
       '56\n                        Yaşında',
       '90\n                        Yaşında',
       '75\n                        Yaşında',
       '70\n                        Yaşında',
       '633\n                        Yaşında',
       '37\n                        Yaşında',
       '80\n                        Yaşında',
       '95\n                        Yaşında',
       '44\n                        Yaşında',
       '100\n                        Yaşında',
       '47\n                        Yaşında',
       '156\n                        Yaşında',
       '99\n                        Yaşında',
       '36\n                        Yaşında',
       '48\n                        Yaşında',
       '51\n                        Yaşında',
       '46\n                        Yaşında',
       '97\n                        Yaşında',
       '88\n                        Yaşında',
       '52\n                        Yaşında',
       '57\n                        Yaşında',
       '66\n                        Yaşında',
       '54\n                        Yaşında',
       '120\n                        Yaşında',
       '94\n                        Yaşında',
       '106\n                        Yaşında',
       '199\n                        Yaşında',
       '119\n                        Yaşında'], dtype=object)

In [439]:
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace ('Sıfır Bina','0')) # we will replace "Sıfır Bina" with 0
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace ('\n',''))
df['age'] = df['celly 3'].apply(lambda x: x.split(' ')[0]).astype(int) # we will split the data with space and we will take the first character and convert it to int

In [440]:
df['age'].unique()

array([ 39,   3,   0,   8,   4,  50,  30,  11,  32,  40,  17,   6,  16,
        12,  35,  28,  20,  10,  31,   5,  21,  33,  29,  15,   7,   1,
        25,  22,  18,   9,  45,  55,  13, 110,  41,  19,  49,  26,  42,
        60,   2,  14,  24,  27,  23,  34,  38,  65,  43,  56,  90,  75,
        70, 633,  37,  80,  95,  44, 100,  47, 156,  99,  36,  48,  51,
        46,  97,  88,  52,  57,  66,  54, 120,  94, 106, 199, 119])

In [441]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   area                9925 non-null   int32
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32
 7   living_room         9925 non-null   int32
 8   age                 9925 non-null   int32
dtypes: int32(4), object(5)
memory usage: 542.9+ KB

In [442]:
df.drop(columns=['celly 3'], inplace=True) # we will drop celly 3 column because we have age column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   area                9925 non-null   int32
 3   celly 4             9712 non-null   object
 4   list-view-location  9925 non-null   object
 5   room                9925 non-null   int32
 6   living_room         9925 non-null   int32
 7   age                 9925 non-null   int32
dtypes: int32(4), object(4)
memory usage: 465.4+ KB

In [443]:
df['celly 4'].unique()

array(['Bahçe Katı', '1. Kat', '8. Kat', 'Ara Kat', nan, '4. Kat',
       '2. Kat', '10. Kat', '5. Kat', '3. Kat', 'Yüksek Giriş', 'Kot 1',
       '6. Kat', 'Teras Katı', '12. Kat', '18. Kat', '14. Kat',
       'Giriş Katı', '11. Kat', '7. Kat', '9. Kat', 'En Üst Kat',
       'Çatı Katı', '21 ve üzeri', '19. Kat', '17. Kat', '15. Kat',
       'Kot 3', '20. Kat', 'Zemin', '16. Kat', 'Yarı Bodrum',
       'Villa Katı', 'Kot 2', '13. Kat', 'Bodrum', 'Bodrum ve Zemin',
       'Tripleks'], dtype=object)

In [444]:
replace_dict = {
    'Kot 3': '-3.Kat',
    'Kot 2': '-2.Kat',
    'Kot 1': '-1.Kat',
    'Zemin': '0.Kat',
    'Bahçe Katı': '0.Kat',
    'Yüksek Giriş': '1.Kat',
    'Giriş Katı': '0.Kat',
    'Ara Kat': '3.Kat',
    'Teras Katı': '5.Kat',
    'En Üst Kat': '5.Kat',
    'Çatı Katı': '6.Kat',
    '21 ve üzeri': '21.Kat',
    'Yarı Bodrum': '0.Kat',
    'Villa Katı': '0.Kat',
    'Bodrum': '-1.Kat',
    'Bodrum ve Zemin': '-1.Kat',
    'Tripleks': '3.Kat',
    'nan': '2.Kat'
}

In [445]:
df['celly 4'] = df['celly 4'].replace(replace_dict.keys(), replace_dict.values()) # we will replace the values in celly 4 column with the values in replace_dict
print(df['celly 4'].unique())

['0.Kat' '1. Kat' '8. Kat' '3.Kat' nan '4. Kat' '2. Kat' '10. Kat'
 '5. Kat' '3. Kat' '1.Kat' '-1.Kat' '6. Kat' '5.Kat' '12. Kat' '18. Kat'
 '14. Kat' '11. Kat' '7. Kat' '9. Kat' '6.Kat' '21.Kat' '19. Kat'
 '17. Kat' '15. Kat' '-3.Kat' '20. Kat' '16. Kat' '-2.Kat' '13. Kat']

In [446]:
print(df['celly 4'].unique())

['0.Kat' '1. Kat' '8. Kat' '3.Kat' nan '4. Kat' '2. Kat' '10. Kat'
 '5. Kat' '3. Kat' '1.Kat' '-1.Kat' '6. Kat' '5.Kat' '12. Kat' '18. Kat'
 '14. Kat' '11. Kat' '7. Kat' '9. Kat' '6.Kat' '21.Kat' '19. Kat'
 '17. Kat' '15. Kat' '-3.Kat' '20. Kat' '16. Kat' '-2.Kat' '13. Kat']

In [447]:
df = df.dropna(subset=['celly 4'])

In [448]:
df['floor'] = df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int) 
 # we will drop the rows with NaN values in floor column

In [449]:
df['floor'].unique()

array([ 0,  1,  8,  3,  4,  2, 10,  5, -1,  6, 12, 18, 14, 11,  7,  9, 21,
       19, 17, 15, -3, 20, 16, -2, 13])

In [450]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9712 non-null   object
 1   list-view-title     21 non-null     object
 2   area                9712 non-null   int32
 3   celly 4             9712 non-null   object
 4   list-view-location  9712 non-null   object
 5   room                9712 non-null   int32
 6   living_room         9712 non-null   int32
 7   age                 9712 non-null   int32
 8   floor               9712 non-null   int32
dtypes: int32(5), object(4)
memory usage: 569.1+ KB

In [451]:
df.head()

,list-view-price,list-view-title,area,celly 4,list-view-location,room,living_room,age,floor
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,39,0.Kat,İstanbul / Şişli / Merkez Mah.,1,0,39,0
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,110,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,3,1,3,1
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,300,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,5,1,0,1
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,90,1. Kat,İstanbul / Pendik / Yenişehir Mah.,2,1,8,1
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,74,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0,4,8

In [452]:
df = df.drop(columns=['celly 4','list-view-title'])

In [453]:
df.head()

,list-view-price,area,list-view-location,room,living_room,age,floor
0,27.0,39,İstanbul / Şişli / Merkez Mah.,1,0,39,0
1,85.0,110,İstanbul / Kadıköy / Kozyatağı Mah.,3,1,3,1
2,590.0,300,İstanbul / Kadıköy / Caddebostan Mah.,5,1,0,1
3,42.5,90,İstanbul / Pendik / Yenişehir Mah.,2,1,8,1
4,35.0,74,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0,4,8

In [454]:
df['list-view-location'].head()

0                     İstanbul / Şişli / Merkez Mah.
1                İstanbul / Kadıköy / Kozyatağı Mah.
2              İstanbul / Kadıköy / Caddebostan Mah.
3                 İstanbul / Pendik / Yenişehir Mah.
4    İstanbul / Bahçelievler / Yenibosna Merkez Mah.
Name: list-view-location, dtype: object

In [455]:
new_cols = df['list-view-location'].str.split('/', expand=True)


df['city'] = new_cols[0].str.strip()
df['district'] = new_cols[1].str.strip()
df['neighbourhood'] = new_cols[2].str.strip()


print(df[['city', 'district', 'neighbourhood']].tail(50))

          city      district          neighbourhood
9871  İstanbul       Maltepe         Küçükyalı Mah.
9872  İstanbul         Şişli      Halaskargazi Mah.
9873  İstanbul      Ümraniye        Dumlupınar Mah.
9874  İstanbul         Şişli             Fulya Mah.
9875  İstanbul        Kartal         Orhantepe Mah.
9876  İstanbul   Sultanbeyli         Orhangazi Mah.
9877  İstanbul  Küçükçekmece             Fatih Mah.
9878  İstanbul      Esenyurt           Mevlana Mah.
9879  İstanbul       Maltepe             Çınar Mah.
9880  İstanbul      Esenyurt           Atatürk Mah.
9881  İstanbul     Kağıthane          Hamidiye Mah.
9882  İstanbul         Tuzla           Aydınlı Mah.
9883  İstanbul      Bağcılar         Mahmutbey Mah.
9884  İstanbul          Şile           Balibey Mah.
9885  İstanbul        Beykoz           Yalıköy Mah.
9886  İstanbul       Silivri              Yeni Mah.
9887  İstanbul    Sancaktepe     Veysel Karani Mah.
9888  İstanbul        Pendik         Yenişehir Mah.
9889  İstanbul    Sancaktepe   Abdurrahmangazi Mah.
9890  İstanbul    Sancaktepe           Atatürk Mah.
9891  İstanbul  Büyükçekmece          Çakmaklı Mah.
9892  İstanbul    Sancaktepe            Meclis Mah.
9893  İstanbul       Sarıyer           Tarabya Mah.
9894  İstanbul     Kağıthane         Çeliktepe Mah.
9895  İstanbul          Şile           Kumbaba Mah.
9896  İstanbul         Tuzla          İstasyon Mah.
9897  İstanbul       Maltepe       Zümrütevler Mah.
9899  İstanbul         Şişli         Teşvikiye Mah.
9900  İstanbul       Beyoğlu       Bereketzade Mah.
9901  İstanbul       Kadıköy           Göztepe Mah.
9902  İstanbul     Kağıthane          Çağlayan Mah.
9905  İstanbul     Kağıthane         Ortabayır Mah.
9907  İstanbul       Maltepe        Aydınevler Mah.
9908  İstanbul       Kadıköy        Fenerbahçe Mah.
9909  İstanbul  Küçükçekmece         Kemalpaşa Mah.
9910  İstanbul         Şişli        Meşrutiyet Mah.
9911  İstanbul      Beşiktaş         Dikilitaş Mah.
9912  İstanbul      Ataşehir             İnönü Mah.
9913  İstanbul   Zeytinburnu           Maltepe Mah.
9914  İstanbul       Avcılar           Ambarlı Mah.
9915  İstanbul  Küçükçekmece             İnönü Mah.
9916  İstanbul       Kadıköy          Caferağa Mah.
9917  İstanbul         Şişli         Teşvikiye Mah.
9918  İstanbul      Beşiktaş          Mecidiye Mah.
9919  İstanbul  Büyükçekmece             Fatih Mah.
9920  İstanbul  Bahçelievler  Kocasinan Merkez Mah.
9921  İstanbul         Fatih       Akşemsettin Mah.
9922  İstanbul    Sancaktepe             Merve Mah.
9923  İstanbul         Tuzla              Cami Mah.
9924  İstanbul  Küçükçekmece        Tevfik Bey Mah.

In [456]:
# Convert Turkish characters to English and make them lowercase
def convert_to_english(text):
    if pd.isnull(text):
        return text
    char_map = {
        'ç': 'c', 'ğ': 'g', 'ı': 'i', 'İ': 'i', 'ö': 'o', 'ş': 's', 'ü': 'u',
        'Ç': 'c', 'Ğ': 'g', 'Ö': 'o', 'Ş': 's', 'Ü': 'u'
    }
    for tr_char, en_char in char_map.items():
        text = text.replace(tr_char, en_char)
    return text.lower() # Lower function

# Apply columns to this function
target_cols = ['city', 'district', 'neighbourhood']

for col in target_cols:
    # Apply the conversion function to each column
    df[col] = df[col].apply(convert_to_english)

In [457]:
df['neighbourhood'] = df['neighbourhood'].str.replace(r'\s+mah.*', '', regex=True).str.strip()


print(df[['city', 'district', 'neighbourhood']].head())

       city      district     neighbourhood
0  istanbul         sisli            merkez
1  istanbul       kadikoy         kozyatagi
2  istanbul       kadikoy       caddebostan
3  istanbul        pendik         yenisehir
4  istanbul  bahcelievler  yenibosna merkez

In [458]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   list-view-price     9712 non-null   object
 1   area                9712 non-null   int32
 2   list-view-location  9712 non-null   object
 3   room                9712 non-null   int32
 4   living_room         9712 non-null   int32
 5   age                 9712 non-null   int32
 6   floor               9712 non-null   int32
 7   city                9712 non-null   object
 8   district            9712 non-null   object
 9   neighbourhood       9712 non-null   object
dtypes: int32(5), object(5)
memory usage: 644.9+ KB

In [459]:
df['list-view-location'].head()

0                     İstanbul / Şişli / Merkez Mah.
1                İstanbul / Kadıköy / Kozyatağı Mah.
2              İstanbul / Kadıköy / Caddebostan Mah.
3                 İstanbul / Pendik / Yenişehir Mah.
4    İstanbul / Bahçelievler / Yenibosna Merkez Mah.
Name: list-view-location, dtype: object

In [460]:
df = df.drop(columns=['list-view-location'])

In [461]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9712 non-null   object
 1   area             9712 non-null   int32
 2   room             9712 non-null   int32
 3   living_room      9712 non-null   int32
 4   age              9712 non-null   int32
 5   floor            9712 non-null   int32
 6   city             9712 non-null   object
 7   district         9712 non-null   object
 8   neighbourhood    9712 non-null   object
dtypes: int32(5), object(4)
memory usage: 569.1+ KB

In [462]:
df['list-view-price'].unique()

array([27.0, 85.0, 590.0, 42.5, 35.0, 45.0, 110.0, 250.0, 28.5, 72.0,
       80.0, 50.0, 95.0, 22.0, 23.0, 38.0, 55.0, 29.0, 17.5, 60.0, 15.0,
       18.0, 32.0, 160.0, 59.5, 52.0, 51.0, 43.0, 120.0, 31.0, 30.0, 21.5,
       '125.000', '39.500', '28.000', '46.000', '22.000', '95.000',
       '32.500', '13.500', '55.000', '23.000', '18.000', '75.000',
       '82.000', '45.000', '260.000', '27.000', '35.000', '40.000',
       '25.000', '39.000', '20.000', '51.000', '32.000', '30.000',
       '13.000', '27.500', '37.900', '15.000', '12.500', '19.000',
       '22.500', '9.500', '90.000', '85.000', '33.500', '120.000',
       '36.000', '30.500', '33.000', '9.750.000', '65.000', '25.500',
       '12.000', '17.000', '80.000', '700.000', '34.500', '26.500',
       '24.000', '240.000', '50.000', '100.000', '70.000', '60.000',
       '36.250', '16.750', '20.500', '575.000', '150.000', '42.000',
       '26.000', '37.000', '81.000', '140.000', '25.020', '45.750',
       '42.500', '24.500', '38.000', '21.500', '17.500', '57.000',
       '34.000', '175.000', '28.250', '67.000', '290.000', '650.000',
       '52.000', '49.000', '11.000', '195.000', '40.250', '57.500',
       '37.500', '69.000', '110.000', '375.000', '170.000', '164.000',
       '73.000', '160.000', '31.000', '59.000', '16.500', '47.000',
       '79.000', '270.000', '77.000', '250.000', '10.000', '145.000',
       '43.000', '67.500', '9.000', '165.000', '36.500', '350.000',
       '53.000', '31.500', '40.500', '62.500', '16.000', '29.900',
       '74.000', '135.000', '14.000', '15.500', '58.000', '105.000',
       '51.500', '330.000', '130.000', '61.000', '235.000', '112.000',
       '96.000', '62.000', '19.500', '18.100', '47.950', '41.000',
       '48.000', '72.000', '124.000', '30.250', '115.000', '93.000',
       '245.000', '83.000', '87.500', '21.000', '155.000', '18.500',
       '54.000', '98.000', '28.500', '52.500', '66.000', '47.500',
       '210.000', '44.000', '99.000', '230.000', '239.000', '8.500',
       '32.100', '30.750', '63.000', '325.000', '400.000', '56.000',
       '56.500', '46.500', '500.000', '38.500', '65.500', '119.000',
       '35.750', '180.000', '78.000', '68.000', '29.000', '36.750',
       '29.500', '200.000', '23.500', '39.999', '84.000', '80.500',
       '15.999', '64.900', '300.000', '48.750', '87.000', '41.500',
       '64.500', '255.000', '14.500', '132.900', '50.200', '16.000.000',
       '950.000', '48.500', '14.999', '11.750', '77.950', '44.250',
       '280.000', '28.750', '24.750', '157.500', '35.950', '44.500',
       '66.500', '755.000', '33.750', '97.900', '600.000', '18.900',
       '49.500', '23.950', '26.750', '97.500', '220.000', '40.750',
       '30.749', '15.001', '1.250.000', '190.000', '43.500', '18.999',
       '84.950', '8.000', '37.300', '31.700', '37.250', '45.950',
       '450.000', '89.000', '34.700', '31.250', '11.500', '4.100.000',
       '45.500', '423.000', '320.000', '82.500', '125.500', '70.500',
       '69.500', '38.499', '275.000', '59.750', '99.500', '295.000',
       '127.000', '620.000', '64.000', '35.500', '204.000', '92.500',
       '520.000', '7.500', '39.750', '54.500', '480.000', '425.000',
       '39.950', '92.000', '25.700', '252.000', '26.250', '1.500',
       '7.000', '6.000', '7.100', '2.500', '5.500', '900.000', '360.000',
       '17.350.000', '1.000', '5.000', '32.750', '29.250', '28.900',
       '133.000', '55.700', '71.000', '490.000', '102.000', '94.000',
       '84.999', 33.0, 100.0, 190.0, 20.0, 65.0, 56.5, 21.0, 40.0, 70.0,
       26.5, 49.0, 25.5, 130.0, 105.0, 75.0, 84.999, 48.0, 42.0, 47.0,
       90.0, 230.0, 380.0, 66.0, 24.5, 94.0, 36.0, 41.5, 26.0, 24.0, 22.5,
       58.0, 13.5, 57.0, 25.0, 17.0, 46.0, 32.5, '380.000', '76.500',
       '118.000', '88.000', '129.000', '215.000', '42.750', '310.000',
       '46.750', '47.750', '147.500', '72.500', '185.000', '152.500',
       '77.500', '365.000', '21.250', '139.500', '225.000', '61.500',
       '26.001', '25.750', '76.000', '132.000', 41.0, 143.0, 71.0, 63.0,
       77.0, 200.0, 74.0, 550.0, 140.0, 99.0, 81.0, 165.0, 36.5, 34.0,
       19.0, 175.0, 49.5, 180.0, 1.0, 51.5, 155.0, 16.0, 350.0, 34.5,
       125.0, 91.0, 72.5, 39.8, 540.0, 44.0, 67.0, 310.0, 760.0, 37.25,
       20.5, 76.0, 150.0, 35.001, 28.0, 650.0, 18.5, 57.5, 48.25, 115.0,
       27.5, 53.0, 83.0, 10.0, 37.0, 13.0, 185.0, 43.5, 69.0, 145.0, 54.0,
       16.5, 61.0, 14.0, 46.5, 82.0, 68.5, 62.5, 220.0, 37.5, 23.5, 137.5,
       44.9, 78.0, 59.0, 47.5, 64.5, 27.999, 56.0, 40.5, 39.0, 225.0,
       195.0, 62.0, 68.0, 18.1, 67.5, 630.0, 88.0, 210.0, 117.5, 18.75,
       260.0, 74.999, 19.65, 35.5, 98.0, '129.500', '29.998', '35.300',
       '109.000', '239.500', '86.000', '138.000', '38.250', '86.900',
       '1.700.000', '98.500', '55.500', '79.500', '189.000', '134.000',
       '137.500', '3.850.000', '74.990', '97.000', '20.600', '2.350.000',
       '23.750', '1.375.000', '29.999', '590.000', '34.250', '39.900',
       '49.900', '370.000', '29.350', '156.000', '78.500', '59.500',
       '435.000', '285.000', '19.900', '58.500', '19.750', 400.0, 29.5,
       12.0, 58.5, 270.0, 135.0, 32.1, 19.75, 300.0, 92.5, 7.5, 8.0,
       450.0, 83.5, 535.0, 245.0, 73.0, 93.0, 30.5, 39.5, 620.0, 410.0,
       6.0, 320.0, 77.777, 87.0, 365.0, 79.0, 7.0, 86.0, 19.5, 52.5,
       215.0, 38.5, 31.5, 139.5, 170.0, 25.75, 119.0, 89.0, 178.5, 11.5,
       45.5, 360.0, 25.02, 290.0, 325.0, 79.5, 275.0, 850.0, 240.0, 44.5,
       38.75, 33.5, 735.0, 11.0, 440.0, '23.250', '26.850', '53.500',
       '179.000', '24.800', '2.850.000', '96.500', '149.999', '49.999',
       '585.000', '24.250', '38.750', '20.750', '117.000', '6.500',
       '445.000', '69.900', '205.000', '102.500', '50.500', '550.000',
       '1.800.000', '33.200', '91.000', '850.000', '18.200', '23.999',
       '3.800', '68.750', '17.999', '340.000', '137.000', '390.000',
       '249.000'], dtype=object)

In [463]:
df['list-view-price'] = df['list-view-price'].astype(str).apply(lambda x:x.replace('.','')) 
df['price'] = df['list-view-price'].astype(int)

In [464]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9712 non-null   object
 1   area             9712 non-null   int32
 2   room             9712 non-null   int32
 3   living_room      9712 non-null   int32
 4   age              9712 non-null   int32
 5   floor            9712 non-null   int32
 6   city             9712 non-null   object
 7   district         9712 non-null   object
 8   neighbourhood    9712 non-null   object
 9   price            9712 non-null   int32
dtypes: int32(6), object(4)
memory usage: 607.0+ KB

In [465]:
df['price'].unique()

array([     270,      850,     5900,      425,      350,      450,
           1100,     2500,      285,      720,      800,      500,
            950,      220,      230,      380,      550,      290,
            175,      600,      150,      180,      320,     1600,
            595,      520,      510,      430,     1200,      310,
            300,      215,   125000,    39500,    28000,    46000,
          22000,    95000,    32500,    13500,    55000,    23000,
          18000,    75000,    82000,    45000,   260000,    27000,
          35000,    40000,    25000,    39000,    20000,    51000,
          32000,    30000,    13000,    27500,    37900,    15000,
          12500,    19000,    22500,     9500,    90000,    85000,
          33500,   120000,    36000,    30500,    33000,  9750000,
          65000,    25500,    12000,    17000,    80000,   700000,
          34500,    26500,    24000,   240000,    50000,   100000,
          70000,    60000,    36250,    16750,    20500,   575000,
         150000,    42000,    26000,    37000,    81000,   140000,
          25020,    45750,    42500,    24500,    38000,    21500,
          17500,    57000,    34000,   175000,    28250,    67000,
         290000,   650000,    52000,    49000,    11000,   195000,
          40250,    57500,    37500,    69000,   110000,   375000,
         170000,   164000,    73000,   160000,    31000,    59000,
          16500,    47000,    79000,   270000,    77000,   250000,
          10000,   145000,    43000,    67500,     9000,   165000,
          36500,   350000,    53000,    31500,    40500,    62500,
          16000,    29900,    74000,   135000,    14000,    15500,
          58000,   105000,    51500,   330000,   130000,    61000,
         235000,   112000,    96000,    62000,    19500,    18100,
          47950,    41000,    48000,    72000,   124000,    30250,
         115000,    93000,   245000,    83000,    87500,    21000,
         155000,    18500,    54000,    98000,    28500,    52500,
          66000,    47500,   210000,    44000,    99000,   230000,
         239000,     8500,    32100,    30750,    63000,   325000,
         400000,    56000,    56500,    46500,   500000,    38500,
          65500,   119000,    35750,   180000,    78000,    68000,
          29000,    36750,    29500,   200000,    23500,    39999,
          84000,    80500,    15999,    64900,   300000,    48750,
          87000,    41500,    64500,   255000,    14500,   132900,
          50200, 16000000,   950000,    48500,    14999,    11750,
          77950,    44250,   280000,    28750,    24750,   157500,
          35950,    44500,    66500,   755000,    33750,    97900,
         600000,    18900,    49500,    23950,    26750,    97500,
         220000,    40750,    30749,    15001,  1250000,   190000,
          43500,    18999,    84950,     8000,    37300,    31700,
          37250,    45950,   450000,    89000,    34700,    31250,
          11500,  4100000,    45500,   423000,   320000,    82500,
         125500,    70500,    69500,    38499,   275000,    59750,
          99500,   295000,   127000,   620000,    64000,    35500,
         204000,    92500,   520000,     7500,    39750,    54500,
         480000,   425000,    39950,    92000,    25700,   252000,
          26250,     1500,     7000,     6000,     7100,     5500,
         900000,   360000, 17350000,     1000,     5000,    32750,
          29250,    28900,   133000,    55700,    71000,   490000,
         102000,    94000,    84999,      330,     1900,      200,
            650,      565,      210,      400,      700,      265,
            490,      255,     1300,     1050,      750,      480,
            420,      470,      900,     2300,     3800,      660,
            245,      940,      360,      415,      260,      240,
            225,      580,      135,      570,      250,      170,
            460,      325,   380000,    76500,   118000,    88000,
         129000,   215000,    42750,   310000,    46750,    47750,
         147500,    72500,   185000,   152500,    77500,   365000,
          21250,   139500,   225000,    61500,    26001,    25750,
          76000,   132000,      410,     1430,      710,      630,
            770,     2000,      740,     1400,      990,      810,
           1650,      365,      340,      190,     1750,      495,
           1800,       10,      515,     1550,      160,     3500,
            345,     1250,      910,      725,      398,     5400,
            440,      670,     3100,     7600,     3725,      205,
            760,    35001,      280,     6500,      185,      575,
           4825,     1150,      275,      530,      830,      100,
            370,      130,     1850,      435,      690,     1450,
            540,      165,      610,      140,      465,      820,
            685,      625,     2200,      375,      235,     1375,
            449,      780,      590,      475,      645,    27999,
            560,      405,      390,     2250,     1950,      620,
            680,      181,      675,     6300,      880,     2100,
           1175,     1875,     2600,    74999,     1965,      355,
            980,   129500,    29998,    35300,   109000,   239500,
          86000,   138000,    38250,    86900,  1700000,    98500,
          55500,    79500,   189000,   134000,   137500,  3850000,
          74990,    97000,    20600,  2350000,    23750,  1375000,
          29999,   590000,    34250,    39900,    49900,   370000,
          29350,   156000,    78500,    59500,   435000,   285000,
          19900,    58500,    19750,     4000,      295,      120,
            585,     2700,     1350,      321,     1975,     3000,
            925,       75,       80,     4500,      835,     5350,
           2450,      730,      930,      305,      395,     6200,
           4100,       60,     3200,    77777,      870,     3650,
            790,       70,      860,      195,      525,     2150,
            385,      315,     1395,     1700,     2575,     1190,
            890,     1785,      115,      455,     3600,     2502,
           2900,     3250,      795,     2750,     2400,      445,
           3875,      335,     7350,      110,     4400,    23250,
          26850,    53500,   179000,    24800,  2850000,    96500,
         149999,    49999,   585000,    24250,    38750,    20750,
         117000,   445000,    69900,   205000,   102500,    50500,
         550000,  1800000,    33200,    91000,   850000,    18200,
          23999,    68750,    17999,   340000,   137000,   390000,
         249000])

In [466]:
df.drop(df[df['price'] < 2500].index, inplace=True)
df['price'].unique()

array([    5900,     2500,   125000,    39500,    28000,    46000,
          22000,    95000,    32500,    13500,    55000,    23000,
          18000,    75000,    82000,    45000,   260000,    27000,
          35000,    40000,    25000,    39000,    20000,    51000,
          32000,    30000,    13000,    27500,    37900,    15000,
          12500,    19000,    22500,     9500,    90000,    85000,
          33500,   120000,    36000,    30500,    33000,  9750000,
          65000,    25500,    12000,    17000,    80000,   700000,
          34500,    26500,    24000,   240000,    50000,   100000,
          70000,    60000,    36250,    16750,    20500,   575000,
         150000,    42000,    26000,    37000,    81000,   140000,
          25020,    45750,    42500,    24500,    38000,    21500,
          17500,    57000,    34000,   175000,    28250,    67000,
         290000,   650000,    52000,    49000,    11000,   195000,
          40250,    57500,    37500,    69000,   110000,   375000,
         170000,   164000,    73000,   160000,    31000,    59000,
          16500,    47000,    79000,   270000,    77000,   250000,
          10000,   145000,    43000,    67500,     9000,   165000,
          36500,   350000,    53000,    31500,    40500,    62500,
          16000,    29900,    74000,   135000,    14000,    15500,
          58000,   105000,    51500,   330000,   130000,    61000,
         235000,   112000,    96000,    62000,    19500,    18100,
          47950,    41000,    48000,    72000,   124000,    30250,
         115000,    93000,   245000,    83000,    87500,    21000,
         155000,    18500,    54000,    98000,    28500,    52500,
          66000,    47500,   210000,    44000,    99000,   230000,
         239000,     8500,    32100,    30750,    63000,   325000,
         400000,    56000,    56500,    46500,   500000,    38500,
          65500,   119000,    35750,   180000,    78000,    68000,
          29000,    36750,    29500,   200000,    23500,    39999,
          84000,    80500,    15999,    64900,   300000,    48750,
          87000,    41500,    64500,   255000,    14500,   132900,
          50200, 16000000,   950000,    48500,    14999,    11750,
          77950,    44250,   280000,    28750,    24750,   157500,
          35950,    44500,    66500,   755000,    33750,    97900,
         600000,    18900,    49500,    23950,    26750,    97500,
         220000,    40750,    30749,    15001,  1250000,   190000,
          43500,    18999,    84950,     8000,    37300,    31700,
          37250,    45950,   450000,    89000,    34700,    31250,
          11500,  4100000,    45500,   423000,   320000,    82500,
         125500,    70500,    69500,    38499,   275000,    59750,
          99500,   295000,   127000,   620000,    64000,    35500,
         204000,    92500,   520000,     7500,    39750,    54500,
         480000,   425000,    39950,    92000,    25700,   252000,
          26250,     7000,     6000,     7100,     5500,   900000,
         360000, 17350000,     5000,    32750,    29250,    28900,
         133000,    55700,    71000,   490000,   102000,    94000,
          84999,     3800,   380000,    76500,   118000,    88000,
         129000,   215000,    42750,   310000,    46750,    47750,
         147500,    72500,   185000,   152500,    77500,   365000,
          21250,   139500,   225000,    61500,    26001,    25750,
          76000,   132000,     3500,     5400,     3100,     7600,
           3725,    35001,     6500,     4825,    27999,     6300,
           2600,    74999,   129500,    29998,    35300,   109000,
         239500,    86000,   138000,    38250,    86900,  1700000,
          98500,    55500,    79500,   189000,   134000,   137500,
        3850000,    74990,    97000,    20600,  2350000,    23750,
        1375000,    29999,   590000,    34250,    39900,    49900,
         370000,    29350,   156000,    78500,    59500,   435000,
         285000,    19900,    58500,    19750,     4000,     2700,
           3000,     4500,     5350,     6200,     4100,     3200,
          77777,     3650,     2575,     3600,     2502,     2900,
           3250,     2750,     3875,     7350,     4400,    23250,
          26850,    53500,   179000,    24800,  2850000,    96500,
         149999,    49999,   585000,    24250,    38750,    20750,
         117000,   445000,    69900,   205000,   102500,    50500,
         550000,  1800000,    33200,    91000,   850000,    18200,
          23999,    68750,    17999,   340000,   137000,   390000,
         249000])

In [467]:
df = df.drop(columns=['list-view-price']) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7727 entries, 2 to 9924
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   area           7727 non-null   int32
 1   room           7727 non-null   int32
 2   living_room    7727 non-null   int32
 3   age            7727 non-null   int32
 4   floor          7727 non-null   int32
 5   city           7727 non-null   object
 6   district       7727 non-null   object
 7   neighbourhood  7727 non-null   object
 8   price          7727 non-null   int32
dtypes: int32(6), object(3)
memory usage: 422.6+ KB

In [468]:
df.to_csv('cleaned_data.csv', index=False)